[build]
  command = "pnpm run build"
  publish = "public/build"
  functions = "netlify/functions"

[dev]
  command = "pnpm run dev"
  port = 5173
  publish = "public/build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version" 